export function clientLenguaje(x) {
  let bandera = true;

  bandera = x === 0 ? true : false;

  let lenguaje = {
    language: " ",
    user: " ",
    password: " ",
    signIn: " ",
    recoverPassword: " ",
    messageWrongPU: " ",
    accessDenied: " ",
    sendEmailMessage: " ",
    additionalInformation: " ",
    regimeWorker: " ",
    scheme: " ",
    otherScheme: " ",
    socialNumber: " ",
    infonavit: " ",
    fonacot: " ",
    payform: "",
    accontN: " ",
    cardN: " ",
    bank: " ",
    other: " ",
    workingInformation: " ",
    job: " ",
    monthlySalary: " ",
    dateOfSeniority: " ",
    jobLocation: " ",
    otherJobLocation: " ",
    journey: " ",
    beneficiary: " ",
    relationchipBeneficiary: " ",
    close: " ",
    personalInfo: " ",
    key: " ",
    name: " ",
    lastName: " ",
    secondLastName: " ",
    bDay: " ",
    civilStatus: " ",
    gender: " ",
    male: " ",
    female: " ",
    country: " ",
    city: " ",
    nacionality: " ",
    contactInfo: " ",
    street: " ",
    number: " ",
    fracc: " ",
    municipality: " ",
    addresState: " ",
    zipCode: " ",
    cel: " ",
    tel: " ",
    news: " ",
    logOut: " ",
    day: " ",
    punches: " ",
    notesA: " ",
    snackbarmsn: " ",
    undo: " ",
    hours: " ",
    passwordRecovery: " ",
    addNewPass: " ",
    repitPass: " ",
    changepass: " ",
    cancel: " ",
    profile: " ",
    collaborators: " ",
    reports: " ",
    conf: " ",
    serviceCol: " ",
    personalData: " ",
    laborData: " ",
    education: " ",
    userData: " ",
    currentPeriod: " ",
    previousPeriod: " ",
    enterEmail: " ",
    sendEmail: " ",
    origin: " ",
    addres: " ",
    edit: " ",
    single: " ",
    married: " ",
    divorced: " ",
    widower: " ",
    freeUnion: " ",
    back: " ",
    next: " ",
    save: " "
  };
  if (bandera) {
    lenguaje = {
      language: "ENG",
      user: "Usuario",
      password: "Contraseña",
      signIn: "Ingresar",
      other: "Otro",
      recoverPassword: "Recuperar Contraseña",
      messageWrongPU: "Usuario y/o Contraseña Incorrectos.",
      accessDenied: "Acceso Denegado",
      sendEmailMessage:
        "se a enviado un correo con el link para cambiar la contraseña a: ",
      additionalInformation: "Información Adicional",
      regimeWorker: "Régimen de contratación del trabajador",
      scheme: "Esquema",
      otherScheme: "Otro esquema",
      socialNumber: "(NSS) Número de seguridad social",
      infonavit: "Infonavit",
      fonacot: "Fonacot",
      payform: "Forma de pago",
      accontN: "Numero de Cuenta",
      cardN: "Numero de Tarjeta",
      bank: "Bnaco",
      workingInformation: "Informacion Laboral",
      job: "Puesto",
      monthlySalary: "Sueldo Mensual",
      dateOfSeniority: "Fecha de antigüedad",
      jobLocation: "Ubicacion Laboral",
      otherJobLocation: "Otra Ubicacion Laboral",
      journey: "Tipo de Jornada",
      beneficiary: "Beneficiario",
      relationchipBeneficiary: "Parentesco del beneficiario",
      close: "Cerrar",
      personalInfo: "Informacion Personal",
      key: "Clave",
      name: "Nombre(s)",
      lastName: "Apellido Paterno",
      secondLastName: "Apellido Materno",
      bDay: "Fecha de nacimiento",
      civilStatus: "Estado Civil",
      gender: "Sexo",
      male: "Masculino",
      female: "Femenino",
      country: "País",
      city: "Ciudad",
      nationality: "Nacionalidad",
      contactInfo: "DATOS DE CONTACTO",
      street: "Calle",
      number: "Numero",
      fracc: "Colonia",
      municipality: "Municipio",
      addresState: "Estado",
      zipCode: "Codigo Postal",
      cel: "Celular",
      tel: "Telefono de Casa",
      news: "Novedades",
      logOut: "Cerrar sesion",
      day: "Dia",
      punches: "Checadas",
      notesA: "Notas archivadas",
      snackbarmsn: "Abrir simple Snackbar",
      undo: "Deshacer",
      hours: "Horas",
      passwordRecovery: "Recuperación de contraseña",
      addNewPass: "Agregue nueva contraseña",
      repitPass: "Repita la nueva contraseña",
      changepass: "Cmabiar contraseña",
      cancel: "cancelar",
      profile: "Perfil",
      collaborators: "Colaboradores",
      reports: "Reoportes",
      conf: "Configuraciones",
      serviceCol: "Servicio al Colaborador",
      personalData: "DATOS PERSONALES",
      laborData: "DATOS LABORALES",
      addData: "Datos Adicionales (Datos Laborales)",
      education: "EDUCACION/EXPERIENCIA",
      userData: "DATOS USUARIO",
      currentPeriod: "Periodo Actual",
      previousPeriod: "Periodo Anterior",
      enterEmail: "Ingresar Correo Electrónico",
      sendEmail: "Enviar correo",
      origin: "LUGAR DE NACIMIENTO",
      addres: "DIRECCION",
      edit: "Editar",
      single: "Soltero",
      married: "Casado",
      divorced: "Divorciado",
      widower: "Viudo",
      freeUnion: "Union Libre",
      back: "ATRAS",
      next: "SIGUIENTE",
      save: "GUARDAR"
    };
  } else {
    lenguaje = {
      language: "ESP",
      user: "User",
      password: "Password",
      signIn: "Sign In",
      recoverPassword: "Recover Password",
      messageWrongPU: "Incorrect username and / or password.",
      accessDenied: "Access Denied",
      sendEmailMessage:
        "an email has been sent with the link to change the password to: ",
      additionalInformation: "Additional Information",
      regimeWorker: "Worker hiring regime",
      scheme: "Scheme",
      otherScheme: "Other Scheme",
      socialNumber: "Social Number",
      infonavit: "Infonavit",
      fonacot: "Fonacot",
      payform: "Way to pay",
      accontN: "Account Number",
      cardN: "Card Number",
      bank: "Bank",
      other: "Other",
      workingInformation: "Working Information",
      job: "Job",
      monthlySalary: "Monthly Salary",
      dateOfSeniority: "Date of seniority",
      jobLocation: "Job Location",
      otherJobLocation: "Other Job Location",
      journey: "Type of Journey",
      beneficiary: "Beneficiary",
      relationchipBeneficiary: "Relationship of the beneficiary",
      close: "Closed",
      personalInfo: "Personal Information",
      key: "Key",
      name: "Name",
      lastName: "Last Name",
      secondLastName: "Second Last Name",
      bDay: "Birthdate",
      civilStatus: "Civil Status",
      gender: "Gender",
      male: "Male",
      female: "Female",
      country: "Country",
      city: "City",
      nationality: "Nationality",
      contactInfo: "CONTACT INFORMATION",
      street: "Street",
      number: "Number",
      fracc: "Suburb",
      municipality: "Town",
      addresState: "State",
      zipCode: "Zip Code",
      cel: "Mobile",
      tel: "Telephone",
      news: "News",
      logOut: "Log Out",
      day: "Day",
      punches: "Punches",
      notesA: "Note Archived",
      snackbarmsn: "Open simple Snackbar",
      undo: "Undo",
      hours: "Hours",
      passwordRecovery: "Password recovery",
      addNewPass: "Add new Password",
      repitPass: "Repeat the new password",
      changepass: "change Password",
      cancel: "Cancel",
      profile: "Profile",
      collaborators: "Collaborators",
      reports: "Reports",
      conf: "Configurations",
      serviceCol: "Service to the Collaborator",
      personalData: "PERSONAL DATA",
      laborData: "LABOR DATA",
      addData: "Aditional Data (Labor Data)",
      education: "EDUCATION/EXPERIENCE",
      userData: "USER DATA",
      currentPeriod: "Current Period",
      previousPeriod: "Previous Period",
      enterEmail: "Enter Email",
      sendEmail: "Send Email",
      origin: "ORIGIN",
      addres: "ADDRESS",
      edit: "Edit",
      single: "Single",
      married: "Married",
      divorced: "Divorced",
      widower: "Widrower",
      freeUnion: "Free Union",
      back: "BACK",
      next: "NEXT",
      save: "SAVE"
    };
  }
  return lenguaje;
}
