export const countries = [
  { value: "Afganistán" },
  { value: "Akrotiri" },
  { value: "Albania" },
  { value: "Alemania" },
  { value: "Andorra" },
  { value: "Angola" },
  { value: "Anguila" },
  { value: "Antártida" },
  { value: "Antigua y Barbuda" },
  { value: "Antillas Neerlandesas" },
  { value: "Arabia Saudí" },
  { value: "Arctic Ocean" },
  { value: "Argelia" },
  { value: "Argentina" },
  { value: "Armenia" },
  { value: "Aruba" },
  { value: "Ashmore andCartier Islands" },
  { value: "Atlantic Ocean" },
  { value: "Australia" },
  { value: "Austria" },
  { value: "Azerbaiyán" },
  { value: "Bahamas" },
  { value: "Bahráin" },
  { value: "Bangladesh" },
  { value: "Barbados" },
  { value: "Bélgica" },
  { value: "Belice" },
  { value: "Benín" },
  { value: "Bermudas" },
  { value: "Bielorrusia" },
  { value: "Birmania Myanmar" },
  { value: "Bolivia" },
  { value: "Bosnia y Hercegovina" },
  { value: "Botsuana" },
  { value: "Brasil" },
  { value: "Brunéi" },
  { value: "Bulgaria" },
  { value: "Burkina Faso" },
  { value: "Burundi" },
  { value: "Bután" },
  { value: "Cabo Verde" },
  { value: "Camboya" },
  { value: "Camerún" },
  { value: "Canadá" },
  { value: "Chad" },
  { value: "Chile" },
  { value: "China" },
  { value: "Chipre" },
  { value: "Clipperton Island" },
  { value: "Colombia" },
  { value: "Comoras" },
  { value: "Congo" },
  { value: "Coral Sea Islands" },
  { value: "Corea del Norte" },
  { value: "Corea del Sur" },
  { value: "Costa de Marfil" },
  { value: "Costa Rica" },
  { value: "Croacia" },
  { value: "Cuba" },
  { value: "Dhekelia" },
  { value: "Dinamarca" },
  { value: "Dominica" },
  { value: "Ecuador" },
  { value: "Egipto" },
  { value: "El Salvador" },
  { value: "El Vaticano" },
  { value: "Emiratos Árabes Unidos" },
  { value: "Eritrea" },
  { value: "Eslovaquia" },
  { value: "Eslovenia" },
  { value: "España" },
  { value: "Estados Unidos" },
  { value: "Estonia" },
  { value: "Etiopía" },
  { value: "Filipinas" },
  { value: "Finlandia" },
  { value: "Fiyi" },
  { value: "Francia" },
  { value: "Gabón" },
  { value: "Gambia" },
  { value: "Gaza Strip" },
  { value: "Georgia" },
  { value: "Ghana" },
  { value: "Gibraltar" },
  { value: "Granada" },
  { value: "Grecia" },
  { value: "Groenlandia" },
  { value: "Guam" },
  { value: "Guatemala" },
  { value: "Guernsey" },
  { value: "Guinea" },
  { value: "Guinea Ecuatorial" },
  { value: "Guinea-Bissau" },
  { value: "Guyana" },
  { value: "Haití" },
  { value: "Honduras" },
  { value: "Hong Kong" },
  { value: "Hungría" },
  { value: "India" },
  { value: "Indian Ocean" },
  { value: "Indonesia" },
  { value: "Irán" },
  { value: "Iraq" },
  { value: "Irlanda" },
  { value: "Isla Bouvet" },
  { value: "Isla Christmas" },
  { value: "Isla Norfolk" },
  { value: "Islandia" },
  { value: "Islas Caimán" },
  { value: "Islas Cocos" },
  { value: "Islas Cook" },
  { value: "Islas Feroe" },
  { value: "Islas Georgia del Sur y Sandwich del Sur" },
  { value: "Islas Heard y McDonald" },
  { value: "Islas Malvinas" },
  { value: "Islas Marianas del Norte" },
  { value: "IslasMarshall" },
  { value: "Islas Pitcairn" },
  { value: "Islas Salomón" },
  { value: "Islas Turcas y Caicos" },
  { value: "Islas Vírgenes Americanas" },
  { value: "Islas Vírgenes Británicas" },
  { value: "Israel" },
  { value: "Italia" },
  { value: "Jamaica" },
  { value: "Jan Mayen" },
  { value: "Japón" },
  { value: "Jersey" },
  { value: "Jordania" },
  { value: "Kazajistán" },
  { value: "Kenia" },
  { value: "Kirguizistán" },
  { value: "Kiribati" },
  { value: "Kuwait" },
  { value: "Laos" },
  { value: "Lesoto" },
  { value: "Letonia" },
  { value: "íbano" },
  { value: "Liberia" },
  { value: "Libia" },
  { value: "Liechtenstein" },
  { value: "Lituania" },
  { value: "Luxemburgo" },
  { value: "Macao" },
  { value: "Macedonia" },
  { value: "Madagascar" },
  { value: "Malasia" },
  { value: "Malaui" },
  { value: "Maldivas" },
  { value: "Malí" },
  { value: "Malta" },
  { value: "Man" },
  { value: "Isla de Marruecos" },
  { value: "Mauricio" },
  { value: "Mauritania" },
  { value: "Mayotte" },
  { value: "México" },
  { value: "Micronesia" },
  { value: "Moldavia" },
  { value: "Mónaco" },
  { value: "Mongolia" },
  { value: "Montserrat" },
  { value: "Mozambique" },
  { value: "Namibia" },
  { value: "Nauru" },
  { value: "Navassa Island" },
  { value: "Nepal" },
  { value: "Nicaragua" },
  { value: "Níger" },
  { value: "Nigeria" },
  { value: "Niue" },
  { value: "Noruega" },
  { value: "Nueva Caledonia" },
  { value: "Nueva Zelanda" },
  { value: "Omán" },
  { value: "Pacific Ocean" },
  { value: "Países Bajos" },
  { value: "Pakistán" },
  { value: "Palaos" },
  { value: "Panamá" },
  { value: "Papúa-Nueva Guinea" },
  { value: "Paracel Islands" },
  { value: "Paraguay" },
  { value: "Perú" },
  { value: "Polinesia Francesa" },
  { value: "Polonia" },
  { value: "Portugal" },
  { value: "Puerto Rico" },
  { value: "Qatar" },
  { value: "Reino Unido" },
  { value: "República Centroafricana" },
  { value: "República Checa" },
  { value: "República Democrática del Congo" },
  { value: "República Dominicana" },
  { value: "Ruanda" },
  { value: "Rumania" },
  { value: "Rusia" },
  { value: "Sáhara Occidental" },
  { value: "Samoa" },
  { value: "Samoa Americana" },
  { value: "San Cristóbal y Nieves" },
  { value: "San Marino" },
  { value: "San Pedro y Miquelón" },
  { value: "San Vicente y las Granadinas" },
  { value: "Santa Helena" },
  { value: "Santa Lucía" },
  { value: "Santo Tomé y Príncipe" },
  { value: "Senegal" },
  { value: "Seychelles" },
  { value: "Sierra Leona" },
  { value: "Singapur" },
  { value: "Siria" },
  { value: "Somalia" },
  { value: "Southern Ocean" },
  { value: "Spratly Islands" },
  { value: "Sri Lanka" },
  { value: "Suazilandia" },
  { value: "Sudáfrica" },
  { value: "Sudán" },
  { value: "Suecia" },
  { value: "Suiza" },
  { value: "Surinam" },
  { value: "Svalbard y Jan Mayen" },
  { value: "Tailandia" },
  { value: "Taiwán" },
  { value: "Tanzania" },
  { value: "Tayikistán" },
  { value: "TerritorioBritánicodel Océano Indico" },
  { value: "Territorios Australes Franceses" },
  { value: "Timor Oriental" },
  { value: "Togo" },
  { value: "Tokelau" },
  { value: "Tonga" },
  { value: "Trinidad y Tobago" },
  { value: "Túnez" },
  { value: "Turkmenistán" },
  { value: "Turquía" },
  { value: "Tuvalu" },
  { value: "Ucrania" },
  { value: "Uganda" },
  { value: "Unión Europea" },
  { value: "Uruguay" },
  { value: "Uzbekistán" },
  { value: "Vanuatu" },
  { value: "Venezuela" },
  { value: "Vietnam" },
  { value: "Wake Island" },
  { value: "Wallis y Futuna" },
  { value: "West Bank" },
  { value: "World" },
  { value: "Yemen" },
  { value: "Yibuti" },
  { value: "Zambia" },
  { value: "Zimbabue" }
];

export const statesFromMexico = [
  {
    name: "Distrito Federal",
    code: "MX-DIF"
  },
  {
    name: "Aguascalientes",
    code: "MX-AGU"
  },
  {
    name: "Baja California",
    code: "MX-BCN"
  },
  {
    name: "Baja California Sur",
    code: "MX-BCS"
  },
  {
    name: "Campeche",
    code: "MX-CAM"
  },
  {
    name: "Chiapas",
    code: "MX-CHP"
  },
  {
    name: "Chihuahua",
    code: "MX-CHH"
  },
  {
    name: "Coahuila",
    code: "MX-COA"
  },
  {
    name: "Colima",
    code: "MX-COL"
  },
  {
    name: "Durango",
    code: "MX-DUR"
  },
  {
    name: "Guanajuato",
    code: "MX-GUA"
  },
  {
    name: "Guerrero",
    code: "MX-GRO"
  },
  {
    name: "Hidalgo",
    code: "MX-HID"
  },
  {
    name: "Jalisco",
    code: "MX-JAL"
  },
  {
    name: "Michoacán",
    code: "MX-MIC"
  },
  {
    name: "Morelos",
    code: "MX-MOR"
  },
  {
    name: "México",
    code: "MX-MEX"
  },
  {
    name: "Nayarit",
    code: "MX-NAY"
  },
  {
    name: "Nuevo León",
    code: "MX-NLE"
  },
  {
    name: "Oaxaca",
    code: "MX-OAX"
  },
  {
    name: "Puebla",
    code: "MX-PUE"
  },
  {
    name: "Querétaro",
    code: "MX-QUE"
  },
  {
    name: "Quintana Roo",
    code: "MX-ROO"
  },
  {
    name: "San Luis Potosí",
    code: "MX-SLP"
  },
  {
    name: "Sinaloa",
    code: "MX-SIN"
  },
  {
    name: "Sonora",
    code: "MX-SON"
  },
  {
    name: "Tabasco",
    code: "MX-TAB"
  },
  {
    name: "Tamaulipas",
    code: "MX-TAM"
  },
  {
    name: "Tlaxcala",
    code: "MX-TLA"
  },
  {
    name: "Veracruz",
    code: "MX-VER"
  },
  {
    name: "Yucatán",
    code: "MX-YUC"
  },
  {
    name: "Zacatecas",
    code: "MX-ZAC"
  }
];
